// lib/dummy_products.dart
final List<Map<String, dynamic>> dummyProducts = [
  {
    'category': 'อาหารสด',
    'name': 'มะม่วงออร์แกนิก',
    'location': 'เชียงใหม่',
    'price': '฿120',
    'rating': 4,
    'image': 'assets/products-image/mango.jpg',
    'description':
        'มะม่วงออร์แกนิก สดจากสวน ปลอดสารพิษ เหมาะสำหรับสุขภาพดีทุกวัย',
    'sellerName': 'สมชาย ฟาร์มสด',
    'sellerImage': 'assets/sellers-image/somchai.jpg',
  },
  {
    'category': 'งานหัตถกรรม',
    'name': 'ตะกร้าสานไม้ไผ่',
    'location': 'ลำปาง',
    'price': '฿250',
    'rating': 5,
    'image': 'assets/products-image/basket.jpg',
    'description':
        'ตะกร้าสานจากไม้ไผ่ธรรมชาติ เหมาะกับการใช้งานหรือเป็นของตกแต่ง',
    'sellerName': 'แม่หญิงล้านนา',
    'sellerImage': 'assets/sellers-image/maeying.jpg',
  },
  {
    'category': 'แม่และเด็ก',
    'name': 'ขวดนมเด็ก',
    'location': 'สงขลา',
    'price': '฿320',
    'rating': 3.5,
    'image': 'assets/products-image/milk.jpg',
    'description': 'ขวดนมสำหรับทารก ผลิตจากวัสดุปลอดสาร BPA ทนความร้อนสูง',
    'sellerName': 'เบบี้ช็อป',
    'sellerImage': 'assets/sellers-image/babyshop.jpg',
  },
  {
    'category': 'เครื่องมือช่าง',
    'name': 'สว่าน',
    'location': 'กรุงเทพมหานคร',
    'price': '฿1,450',
    'rating': 4,
    'image': 'assets/products-image/drill.jpg',
    'description': 'สว่านไฟฟ้าคุณภาพสูง สำหรับงานช่าง ใช้งานง่าย พกพาสะดวก',
    'sellerName': 'ร้านช่างมือโปร',
    'sellerImage': 'assets/sellers-image/toolpro.jpg',
  },
  {
    'category': 'อาหารสด',
    'name': 'หมึกกล้วย',
    'location': 'สงขลา',
    'price': '฿280',
    'rating': 5,
    'image': 'assets/products-image/squid.jpeg',
    'description':
        'หมึกกล้วยสดจากทะเล สะอาด สดใหม่ รสชาติหวาน กรอบ เหมาะสำหรับทำอาหารหลากหลายเมนู เช่น ผัด เผา หรือแกงจืด',
    'sellerName': 'สงขลา ซีฟู้ด',
    'sellerImage': 'assets/sellers-image/sea.jpg',
  },
];
